//check if login page as it will throw error if the page not including lock.js
if (window.location.pathname.indexOf("login") != -1) {
    Auth0.registerLanguageDictionary("th",
    {
        "error": {
            "forgotPassword": {
                "too_many_requests": "คุณใส่รหัสผ่านเกินจำนวนครั้งที่กำหนด โปรดรอสักครู่ก่อนลองอีกครั้ง ",
                "lock.fallback": "'ขออภัย เกิดข้อผิดพลาดในการขอเปลี่ยนรหัสผ่าน' ",
                "enterprise_email": " 'Your email's domain is part of an Enterprise identity provider. To reset your password, please see your security administrator.' ",
            },
            "login": {
                "blocked_user": "ระงับการใช้งานของผู้เข้าใช้ ",
                "invalid_user_password": "ข้อมูลไม่ถูกต้อง ",
                "lock.fallback": "'ขออภัย เกิดข้อผิดพลาดในการพยายามเข้าสู่ระบบ' ",
                "lock.invalid_code": "รหัสไม่ถูกต้อง ",
                "lock.invalid_email_password": "อีเมลหรือรหัสผ่านไม่ถูกต้อง ",
                "lock.invalid_username_password": "ชื่อผู้ใช้งานหรือรหัสผ่านไม่ถูกต้อง ",
                "lock.network": "เราไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้ โปรดตรวจสอบการเชื่อมต่อของคุณและลองอีกครั้ง ",
                "lock.popup_closed": "หน้าต่างป็อปอัพปิดอยู่ กรุณาลองอีกครั้ง ",
                "lock.unauthorized": "ไม่ได้รับการอณุญาติ โปรดลองอีกครั้ง ",
                "lock.mfa_registration_required": "จำเป็นต้องมีการตรวจสอบสิทธิ์การเข้าถึง แต่อุปกรณ์ของคุณไม่ได้ลงทะเบียนไว้ โปรดลงทะเบียนก่อนดำเนินการต่อ ",
                "lock.mfa_invalid_code": "รหัสไม่ถูกต้อง โปรดลองอีกครั้ง ",
                "password_change_required": "คุณจำเป็นต้องอัปเดตหัสผ่านของคุณ เนื่องจากนี่เป็นครั้งแรกที่คุณเข้าสู่ระบบ หรือระหัสผ่านของคุณหมดอายุแล้ว ",
                "password_leaked": "เราตรวจพบปัญหาด้านความปลอดภัยที่อาจเกิดขึ้นกับบัญชีนี้ เพื่อป้องกันบัญชีของคุณ เราได้ล็อคการเข้าสู่ระบบนี้แล้ว เราได้ส่งอีเมลพร้อมคำแนะนำเกี่ยวกับวิธีการปลดล็อคบัญชีของคุณ ",
                "too_many_attempts": "บัญชีของคุณถูกบล็อกหลังจากพยายามลงชื่อเข้าใช้หลายครั้งติดต่อกัน ",
                "session_missing": "'ไม่สามารถขอการตรวจสอบสิทธิ์ของคุณได้ โปรดลองอีกครั้งหลังจากปิดระบบการค้นหาทั้งหมดที่เปิดอยู่' ",
                "hrd.not_matching_email": "โปรดใช้อีเมลของบริษัทเพื่อเข้าสู่ระบบ ",
            },
            "passwordless": {
                "bad.email": "อีเมลไม่ถูกต้อง ",
                "bad.phone_number": "หมายเลขโทรศัพท์ไม่ถูกต้อง ",
                "lock.fallback": "'ออภัย มีบางอย่างผิดพลาด' ",
            },
            "signUp": {
                "invalid_password": "รหัสผ่านไม่ถูกต้อง ",
                "lock.fallback": "ขออภัย ขณะนี้เกิดข้อผิดพลาดในการสมัครใช้งาน' ",
                "password_dictionary_error": "รหัสผ่านธรรมดาเกินไป ",
                "password_no_user_info_error": "รหัสผ่านซ้ำกับชื่อผู้ใช้งาน ",
                "password_strength_error": "รหัสผ่านคาดเดาง่ายเกินไป ",
                "user_exists": "ชื่อนี้มีผู้ใช้ไปแล้ว ",
                "username_exists": "ชื่อผู้ใช้นี้มีผู้ใช้งานไปแล้ว ",
            }
        },
        "success": {
            "logIn": "ขอบคุณสำหรับการเข้าสู่ระบบ ",
            "forgotPassword": "'เราได้ส่งอีเมลเพื่อตั้งรหัสผ่านใหม่' ",
            "magicLink": "เราได้ส่งลิงก์เพื่อเข้าสู่ระบบ <br /> ไปยัง % s ",
            "signUp": "ขอบคุณสำหรับการลงชื่อเข้าใช้ ",
        },
        "blankErrorHint": "'โปรดกรอกข้อมูลของคุณ",
        "codeInputPlaceholder": "รหัสของคุณ ",
        "databaseEnterpriseLoginInstructions": " ",
        "databaseEnterpriseAlternativeLoginInstructions": "หรือ ",
        "databaseSignUpInstructions": " ",
        "databaseAlternativeSignUpInstructions": "หรือ ",
        "emailInputPlaceholder": "yours@example.com ",
        "enterpriseLoginIntructions": "เข้าสู่ระบบด้วยข้อมูลประจำตัวของบริษัท ",
        "enterpriseActiveLoginInstructions": "โปรดป้อนข้อมูลประจำตัวของบริษัทที่ % s ",
        "failedLabel": "ล้มเหลว! ",
        "forgotPasswordTitle": "ตั้งค่ารหัสผ่านใหม่อีกครั้ง ",
        "forgotPasswordAction": "'ไม่ต้องการจดจำรหัสผ่านของฉัน",
        "forgotPasswordInstructions": "กรุณากรอกอีเมลของคุณ เราจะส่งอีเมลเพื่อตั้งรหัสผ่านใหม่ ",
        "forgotPasswordSubmitLabel": "ส่งอีเมล ",
        "invalidErrorHint": "ไม่ถูกต้อง ",
        "lastLoginInstructions": "ครั้งสุดท้ายคุณเข้าสู่ระบบด้วย ",
        "loginAtLabel": "เข้าสู่ระบบที่ % s ",
        "loginLabel": "เข้าสู่ระบบ ",
        "loginSubmitLabel": "เข้าสู่ระบบ ",
        "loginWithLabel": "เข้าสู่ระบบด้วย % s ",
        "notYourAccountAction": "บัญชีของคุณใช่หรือไม่? ",
        "passwordInputPlaceholder": "รหัสผ่านของคุณ ",
        "passwordStrength": {
            "containsAtLeast": "ประกอบด้วยตัวอักษรประเภท % d  ดังต่อไปนี้ % d  เป็นอย่างน้อย ",
            "identicalChars": "ตัวอักษรเหมือนกันในแถวได้ไม่เกิน % d (เช่น ไม่สามารถใช้ %s ) ",
            "nonEmpty": "โปรดกรอกรหัสผ่าน ",
            "numbers": "ตัวเลข (เช่น 0-9) ",
            "lengthAtLeast": "ตัวอักษรอย่างน้อย % d  ",
            "lowerCase": "ตัวพิมพ์เล็ก (a-z) ",
            "shouldContain": "ควรประกอบด้วย': ",
            "specialCharacters": "สัญลักษณ์พิเศษ (e.g. !@#$%^&*) ",
            "upperCase": "ตัวพิมพ์ใหญ่ (A-Z) ",
        },
        "passwordlessEmailAlternativeInstructions": "หรือป้อนอีเมลของคุณเพื่อลงชื่อเข้าใช้ <br/> หรือสร้างบัญชี ",
        "passwordlessEmailCodeInstructions": "ส่งอีเมลพร้อมรหัสไปที่% s แล้ว ",
        "passwordlessEmailInstructions": "ป้อนอีเมลของคุณเพื่อลงชื่อเข้าใช้ <br/> หรือสร้างบัญชี ",
        "passwordlessSMSAlternativeInstructions": "หรือป้อนหมายเลขโทรศัพท์ของคุณเพื่อลงชื่อเข้าใช้ <br/> หรือสร้างบัญชี ",
        "passwordlessSMSCodeInstructions": "ส่ง SMS พร้อมรหัสไปแล้ว <br/>  ถึง % s ",
        "passwordlessSMSInstructions": "ป้อนหมายเลขโทรศัพท์ของคุณเพื่อลงชื่อเข้าใช้ <br/>  หรือสร้างบัญชี  ",
        "phoneNumberInputPlaceholder": "หมายเลขโทรศัพท์ของคุณ ",
        "resendCodeAction": "คุณได้รับรหัสหรือไม่? ",
        "resendLabel": "ส่งใหม่อีกครั้ง ",
        "resendingLabel": "กำลังส่งใหม่อีกครั้ง... ",
        "retryLabel": "ลองใหม่อีกครั้ง ",
        "sentLabel": "ส่งแล้ว! ",
        "showPassword": "แสดงรหัสผ่าน ",
        "signUpTitle": "ลงชื่อเข้าใช้ ",
        "signUpLabel": "ลงชื่อเข้าใช้ ",
        "signUpSubmitLabel": "ลงชื่อเข้าใช้ ",
        "signUpTerms": " ",
        "signUpWithLabel": "ลงชื่อเข้าใช้ด้วย % s ",
        "socialLoginInstructions": " ",
        "socialSignUpInstructions": " ",
        "ssoEnabled": "Single Sign-On enabled ",
        "submitLabel": "ยืนยัน ",
        "unrecoverableError": "มีบางอย่างผิดพลาด <br />  กรุณาติดต่อ technical support ของคุณ ",
        "usernameFormatErrorHint": "ใช้ตัวอักษร % d-% d  ตัวเลขและสัญลักษณ์ต่อไปนี้': '_', '.', '+', ' -' ",
        "usernameInputPlaceholder": "ชื่อผู้ใช้งานของคุณ ",
        "usernameOrEmailInputPlaceholder": "ชื่อผู้ใช้งาน/อีเมล ",
        "title": "Auth0 ",
        "welcome": "ยินดีต้อนรับ % s! ",
        "windowsAuthInstructions": "คุณเชื่อมต่อจากเครือข่ายองค์กรของคุณ & hellip; ",
        "windowsAuthLabel": "Windows Authentication ",
        "mfaInputPlaceholder": "รหัส  ",
        "mfaLoginTitle": "การยืนยันแบบ 2 ขั้นตอน  ",
        "mfaLoginInstructions": "โปรดป้อนรหัสยืนยันที่สร้างโดยแอพพลิเคชันมือถือของคุณ ",
        "mfaSubmitLabel": "เข้าสู่ระบบ ",
        "mfaCodeErrorHint": "ใช้ %d  ตัวเลข "
    });
}

//password reset page
//as Auth0 does not support similar options (languageDictionary), we have to declare a global function to get language translation
window.GetResetPasswordLangDict = function () {
    return {
        "passwordPlaceholder": "รหัสผ่านใหม่ของคุณ",
        "passwordConfirmationPlaceholder": "ยืนยันรหัสผ่านใหม่ของคุณ",
        "passwordConfirmationMatchError": "โปรดตรวจสอบให้แน่ใจว่ารหัสผ่านที่ได้รับและรหัสผ่านยืนยันเหมือนกัน",
        "passwordStrength": {
            "containsAtLeast": "ประกอบด้วยตัวอักษรประเภท % d  ดังต่อไปนี้ % d  เป็นอย่างน้อย \"",
            "identicalChars": "ตัวอักษรเหมือนกันในแถวได้ไม่เกิน % d  (เช่น ไม่สามารถใช้ \"% s \")",
            "nonEmpty": "ต้องระบุรหัสผ่าน",
            "numbers": "ตัวเลข (เช่น 0-9)",
            "lengthAtLeast": "ตัวอักษรอย่างน้อย % d",
            "lowerCase": "ตัวพิมพ์เล็ก (a-z)",
            "shouldContain": "ควรประกอบด้วย:",
            "specialCharacters": "สัญลักษณ์พิเศษ (เช่น! @ # $% ^ & *)",
            "upperCase": "ตัวพิมพ์ใหญ่ (A-Z)"
        },
        "successMessage": "รหัสผ่านของคุณได้รับการตั้งค่าใหม่เรียบร้อยแล้ว",
        "configurationError": "เกิดข้อผิดพลาด อาจจะมีการตั้งค่าผิดในแบบฟอร์ม ",
        "networkError": "ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้ เครือข่ายมีปัญหา",
        "timeoutError": "ไม่สามารถเชื่อมต่อเซิร์ฟเวอร์ได้ โปรดลองอีกครั้ง",
        "serverError": "มีข้อผิดพลาดในการประมวลผลการตั้งค่ารหัสผ่านใหม่",
        "headerText": "กรอกรหัสผ่านใหม่สำหรับ <br /> {email}",
        "title": "เปลี่ยนรหัสผ่าน",
        "weakPasswordError": "รหัสผ่านคาดเดาง่ายเกินไป",
        "passwordHistoryError": "รหัสผ่านนี้เคยใช้แล้ว"
    }
};
